# This is a basic workflow to help you get started with Actions

name: Delete merged test container

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger 개발서버 젠킨스 아이템 실행 - 테스트 컨테이너 삭제
        run: |
          curl -X POST http://spacecloud:110a3d7506ef0e1c881a7a136798bb8fea@49.236.144.88/job/delete_test_containers/buildWithParameters?SERVICE_NAME=dev-api&BRANCH_NAME=issue/SC-1384&token=72DyQySRcLfCjtyZ
